[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
		\.eggs
		| \.git
		| \.mypy_cache
		| venv*
		| _build
		| build
		| dist
)/
'''